---
# List of packages to be installed via the yum package manager.
minimal:
  version_control:
    - git-core
    - subversion
    - mercurial
  build:
    - cmake
    - gcc
    - gcc-c++
    - gcc-gfortran
    - make
  util:
    - screen
    - unzip
    - tar
    - less
  network:
    - curl
    - wget
libraries:
  - atlas
  - atlas-devel
  - blas
  - blas-devel
  - bzip2-devel
  - freetype-devel
  - gsl-devel
  - lapack
  - lapack-devel
  - libgfortran
  - libpng-devel
  - openssl-devel
  - ncurses-devel
  - libxml2-devel
  - zlib-devel
desktop:
  - gnome-panel
  - freenx
  - gnome-terminal
  - firefox
  - evince
  - xorg-x11-server-Xvfb
programming:
  editors:
    - emacs
    - emacs-common
    - emacs-el
    - vim-X11
    - ctags
  version_control:
    - cvs
    - bzr
  documentation:
  build:
    - swig
    - curl-devel
    - libxslt
    - libxslt-devel
    - xfsprogs
    - glibc
    - glibc-devel
    - zip
    - zziplib-devel
    - xz
    - xz-devel
    - gtk2
    - gtk2-devel
    - globus-openss
    - globus-openssl-devel
    - pcre
    - pcre-devel
    - readline
    - readline-devel
    - rsync
    - librsync
    - librsync-devel
  libraries:
    - tcl-devel
    - tk-devel
    - ImageMagick
    - boost141
    - boost141-devel
    - boost
    - boost-devel
    - openmpi
    - openmpi-devel
    - gd
    - gd-devel
    - libgnomecanvas
    - libgnomecanvas-devel
    - gnome-vfs2
    - gnome-vfs2-devel
    - libgnomeui
    - libgnomeui-devel
    - pango
    - pango-devel
  virtual:
  util:
    - tree
  lang:
    - aspell
distributed:
amazon:
python:
  - python
  - python-devel
  - boost-python-devel
  - numpy
  - python-pip
ruby:
  - ruby
  - ruby-devel
  - rubygems
  - ruby-irb
  - rubygem-rake
r:
  - R
  - R-core
  - libRmath
  - libRmath-devel
perl: 
  - perl
java:
  - ant
  - ant-junit
  - ant-nodeps
  - java-1.7.0-openjdk
  - java-1.7.0-openjdk-devel
  - junit4
erlang:
  - erlang
  - erlang-devel
haskell:
  - ghc
databases:
  mysql:
    - mysql
    - mysql-devel
    - mysql-server
  postgres:
    - postgresql
    - postgresql-devel
    - postgresql-server
  sqlite:
    - sqlite
    - sqlite-devel
  document:
    - mongodb
    - mongodb-devel
    - couchdb
    - tokyocabinet
    - tokyocabinet-devel
  hdf:
    - hdf5
    #- hdf5-devel
math:
  - prover9
  - octave
  - octave-devel
viz:
  - gnuplot
  - ImageMagick
  - ImageMagick-devel
  - graphviz
  - graphviz-devel
web:
  - httpd
  - httpd-devel
  - nginx
bio_general:
bio_search:
bio_alignment:
bio_nextgen:
bio_sequencing:
bio_annotation:
bio_microarray:
bio_visualization:
bio_utils:
phylogeny:
  all:
  needs_64bit:
